// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfq697PUdAndtGSF0_Jlff1Cl6RhoUk5U',
    appId: '1:621881068861:ios:208773df2d65fd97338954',
    messagingSenderId: '621881068861',
    projectId: 'fsnameapp',
    storageBucket: 'fsnameapp.appspot.com',
    iosBundleId: 'com.example.ankiApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3BGtf-G4p2mF4BLOjCSi-GErrbvP8ltM',
    appId: '1:621881068861:web:3de869c9ee4ca376338954',
    messagingSenderId: '621881068861',
    projectId: 'fsnameapp',
    authDomain: 'fsnameapp.firebaseapp.com',
    storageBucket: 'fsnameapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfq697PUdAndtGSF0_Jlff1Cl6RhoUk5U',
    appId: '1:621881068861:ios:208773df2d65fd97338954',
    messagingSenderId: '621881068861',
    projectId: 'fsnameapp',
    storageBucket: 'fsnameapp.appspot.com',
    iosBundleId: 'com.example.ankiApp',
  );

}